variable "resource_group_name" {}
variable "resource_group_location" {}
variable "virtual_network_name" {}
variable "network_interface_frontend" {}
variable "network_interface_backend" {}
variable "pip" {}
variable "sql_server" {}
variable "administrator_login" {}
variable "administrator_login_password" {}
variable "sql_database_name" {}
variable "frontend_vm" {}
variable "backend_vm" {}
variable "admin_username" {}
variable "vm_size" {}
variable "image_publisher" {}
variable "image_offer" {}
variable "image_sku" {}
variable "image_version" {}
variable "admin_password" {}
